sudo: false
language: python
matrix:
  include:
  - python: '2.7'
    install:
    - pip install -r py2-requirements.txt
  - python: '3.5'
    install:
    - pip install -r requirements.txt
  - python: '3.6'
    install:
    - pip install -r requirements.txt
cache:
  directories:
  - '~/.cache/pip'
notifications:
  email:
    on_success: always
before_install:
- pip install -U pip
- pip install wheel
- pip install -r dev-requirements.txt
script:
- manage lint && manage test
env:
  global:
  - secure: aJb+N5HgjalyBNeKIKYe1zl54lZRrcVdw2kt7lN4rDoD40z75FQAwvugWJxhSvPtzt+N+IHkxluStHtud3PwTp2Eb2AAAHOvI0Hz7vpSh9BRjK5uSzmOMTRXH6VCfu9NwbbcjrcB+xxl71EgUsucN7FVZTanqTaimrCA8+D2ang=
  - secure: RqHPGhZWt9ebSL0hlbmkIrgxHAE+D15GUhAXd+yNZ590a6DhTlOtl34HSjVsE5rTWuHx5Biv/orqIcUjHecPjce9FanDo8IB/9Q3aEMoZE3StrJEIVzsz6PObUKw7fkcopjiqgimoCJbsYcDPn4OV5tnspmDFOP4KKojzVF6vYM=
  - secure: Qq7tWageFTKOyDmikm2ye9HMjQA+SRU9/pGoatvP9dCsCCpIRY4tKL6psLDbMoZTWid7xyOzaGa5bZWms4bff6eFlwB0msNY1lJiQoh33Zixl7Vx+tfu836L8KHPKxxY16QY3z0tNR5ogrGs67cRwQqxyjlXTP9cbuwIL1K1zgU=
  - secure: J3OHEHmmk6aXpK5Klx7vDXmcxOkN/ElY+y30WtVadp/AMfDr5KdTPseflLr+aaWmHbJXRiEj15+hzC78T+/VX7Qhm8J/uV+faVa0++z+f16vdJoTyTZZLHrkmLxDCRaayysIACvlU+V7WBRzxS8+nO2oj2ou+tMs8nMExRB+AME=
  - secure: dlhfuDMaxc2lojkGhwJJVnS+sXvLXScq0cjQLZ6L7NlW+E52KGJz+UsDDu1/KU8w1gYexBvEeVkrNXCtqcrzYOs35R7K24eVSH69v1Olho1XYBr03l+/noEMrTYTIBmwMWEU0iTqYpwKuq6aaNVzS6A/3vr9USR2sGLUpttMYD4=
deploy:
  provider: heroku
  api_key:
    secure: OtAueASwNTuZ87qucn8uH4OnOCNJaSQPt1krNdbJIClb4MXltkiGHRnFJfYJWbKSB3DI8WnHVKaeftqRBa838fQWp9Hyl7F12NPE0stam2XMn8aWo9L/7OEOMk4If+pjRvCMYZu5jR354zTgzf7q2YMD8FtCUu6/zgQxcGjyZNs=
  on:
    python: '3.6'
