# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

install: pip install -r requirements/test.txt
script: python manage.py test

after_success:
  # check for pull request
  - if [[ "$TRAVIS_PULL_REQUEST" == "true" ]]; then exit 0; fi

  # Install heroku toolbelt and add remote repo
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh

  # check branch for conditional remote add
  - REPO_NAME=`basename $TRAVIS_REPO_SLUG`
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then git remote add production git@heroku.com:${REPO_NAME}.git; fi
  - if [[ "$TRAVIS_BRANCH" == "features" ]]; then git remote add staging git@heroku.com:${REPO_NAME}.git; fi

  # Turn off warnings about SSH keys:
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  - heroku keys:clear
  - yes | heroku keys:add

  # check branch for conditional push
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then yes | git push production master; fi
  - if [[ "$TRAVIS_BRANCH" == "features" ]]; then yes | git push staging features:master; fi

AWS_ACCESS_KEY_ID:
  secure: XHQglNovdF53LzitzRI5bQxwqP1s2FRhVqVe2mtQnX3fKKWcF9uyX6stjsOFrKccG1T5LN6c6wz/92JiPR8kASZ/tYbct1bVctcCVAn+g8CpolIgJAHTx1AkmYr5l1z/+Rhbw4Xp3uUvzuZYPzN1WLXuEgS/MePVu1KaV+G9vr0=
AWS_SECRET_ACCESS_KEY:
  secure: N+xY8u2XVlqHZNZZQXsgdVDtnYscJkAkhNCsXL0r4UhLg4jL5ys594tVcEwpwT7RvsEhm5h0zTkLMkpyQofg8FpWCj18k9AamPZkEG43el7jvG8L1WGHhGrm/HPQsU8HdcFq8D/yG6vsKTlAQFrV2hZeuUl60gcsO4osl20eJxs=
AWS_ASSOCIATE_TAG:
  secure: JXKv8IE4IChsPAk2SUiduHB2ZLC0tnlE6IRbIZvgZuRsU/pCcURawOuFAUdjM38RBm0ZvL9Oy0UcaHjCsWvXaUsJff9wGTBz9XZ03jzK5FW1ibtxOrBTIGz1tm72HR6JFJNmvRIHzoolY8spLS/uLZ2uB3n65ZsXM5tbG+QdQ+I=
